apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  type: git
  params:
  - name: url
    value: https://devtools.belastingdienst.nl/bitbucket/scm/~wolfj09/spring-petclinic.git