apiVersion: v1
kind: List
metadata:
  name: petclinic-pipeline
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: petclinic
    name: petclinic-pipeline
  spec:
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: develop
        uri: "ssh://git@git.belastingdienst.nl:7999/~wolfj09/spring-petclinic.git"
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: buildpipeline/Jenkinsfile.groovy
    triggers:
      - generic:
          secret: 9oFZQ9gNk3PZBjPbHXIB
        type: Generic
      - type: ConfigChange
